import React, { useState } from 'react';
import { useRoom } from '../context/RoomContext';
import { motion, AnimatePresence } from 'framer-motion';
import { Code2, Users, Trophy, ChevronRight, Layout, Zap, Shield } from 'lucide-react';

const LandingPage: React.FC = () => {
    const { setUsername, username, createRoom, joinRoom } = useRoom();
    const [roomCode, setRoomCode] = useState('');
    const [isJoining, setIsJoining] = useState(false);
    const [settings, setSettings] = useState({
        difficulty: 'Medium',
        language: 'javascript',
        type: 'Algorithms'
    });

    const handleCreate = (e: React.FormEvent) => {
        e.preventDefault();
        if (!username) return alert('Enter username');
        createRoom(settings);
    };

    const handleJoin = (e: React.FormEvent) => {
        e.preventDefault();
        if (!username || !roomCode) return alert('Enter username and room code');
        joinRoom(roomCode);
    };

    return (
        <div className="w-full max-w-6xl mx-auto px-4 py-12 flex flex-col items-center">


            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center mb-16"
            >
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-sm font-medium mb-6">
                    <Zap size={14} />
                    <span>Next Gen Competitive Coding</span>
                </div>
                <h1 className="text-6xl md:text-7xl font-bold mb-6 tracking-tight">
                    Battle with <span className="brand-gradient">Code.</span>
                </h1>
                <p className="text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
                    The ultimate real-time coding competition platform. Challenge friends,
                    solve AI-generated problems, and climb the leaderboard.
                </p>
            </motion.div>

            <div className="grid lg:grid-cols-2 gap-12 items-start w-full">

                <div className="grid sm:grid-cols-2 gap-4 hidden lg:grid">
                    <div className="glass-card p-6 border-indigo-500/10">
                        <div className="w-12 h-12 bg-indigo-500/20 rounded-xl flex items-center justify-center mb-4 text-indigo-400">
                            <Code2 size={24} />
                        </div>
                        <h3 className="text-lg font-bold mb-2">AI Problems</h3>
                        <p className="text-slate-400 text-sm">Unique algorithmic challenges generated by Llama 3 on the fly.</p>
                    </div>
                    <div className="glass-card p-6 border-pink-500/10">
                        <div className="w-12 h-12 bg-pink-500/20 rounded-xl flex items-center justify-center mb-4 text-pink-400">
                            <Users size={24} />
                        </div>
                        <h3 className="text-lg font-bold mb-2">Real-time</h3>
                        <p className="text-slate-400 text-sm">Instantly sync code with competitors and chat as you solve.</p>
                    </div>
                    <div className="glass-card p-6 border-emerald-500/10">
                        <div className="w-12 h-12 bg-emerald-500/20 rounded-xl flex items-center justify-center mb-4 text-emerald-400">
                            <Shield size={24} />
                        </div>
                        <h3 className="text-lg font-bold mb-2">Secure</h3>
                        <p className="text-slate-400 text-sm">Isolated execution environment keeps your code safe and fast.</p>
                    </div>
                    <div className="glass-card p-6 border-amber-500/10">
                        <div className="w-12 h-12 bg-amber-500/20 rounded-xl flex items-center justify-center mb-4 text-amber-400">
                            <Trophy size={24} />
                        </div>
                        <h3 className="text-lg font-bold mb-2">Compete</h3>
                        <p className="text-slate-400 text-sm">Earn points for speed, accuracy, and code optimization.</p>
                    </div>
                </div>
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="glass-card p-8 relative overflow-hidden"
                >
                    <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 blur-3xl -mr-16 -mt-16" />

                    <div className="segmented-control mb-8">
                        <div
                            className="slider"
                            style={{ transform: isJoining ? 'translateX(100%)' : 'translateX(0)' }}
                        />
                        <button
                            className={!isJoining ? 'active' : ''}
                            onClick={() => setIsJoining(false)}
                        >
                            Host Room
                        </button>
                        <button
                            className={isJoining ? 'active' : ''}
                            onClick={() => setIsJoining(true)}
                        >
                            Join Room
                        </button>
                    </div>
                    <div className="space-y-6">
                        <div>
                            <label className="block text-sm font-semibold mb-2 text-slate-300">Choose a handle</label>
                            <input
                                type="text"
                                className="input-premium"
                                placeholder="Enter your username..."
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                            />
                        </div>
                        <AnimatePresence mode="wait">
                            {isJoining ? (
                                <motion.form
                                    key="join"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -10 }}
                                    onSubmit={handleJoin}
                                    className="space-y-4"
                                >
                                    <div>
                                        <label className="block text-sm font-semibold mb-2 text-slate-300">Room Credentials</label>
                                        <input
                                            type="text"
                                            className="input-premium font-mono tracking-widest"
                                            placeholder="XXXXXX"
                                            value={roomCode}
                                            onChange={(e) => setRoomCode(e.target.value.toUpperCase())}
                                        />
                                    </div>
                                    <button className="btn-premium w-full mt-4">
                                        Join Arena <ChevronRight size={18} />
                                    </button>
                                </motion.form>
                            ) : (
                                <motion.form
                                    key="create"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -10 }}
                                    onSubmit={handleCreate}
                                    className="space-y-4"
                                >
                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-sm font-semibold mb-2 text-slate-300">Difficulty</label>
                                            <select
                                                className="input-premium text-sm pr-10 cursor-pointer"
                                                value={settings.difficulty}
                                                onChange={(e) => setSettings({ ...settings, difficulty: e.target.value })}
                                            >
                                                <option>Easy</option>
                                                <option>Medium</option>
                                                <option>Hard</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-sm font-semibold mb-2 text-slate-300">Language</label>
                                            <select
                                                className="input-premium text-sm pr-10 cursor-pointer"
                                                value={settings.language}
                                                onChange={(e) => setSettings({ ...settings, language: e.target.value })}
                                            >
                                                <option value="javascript">JavaScript</option>
                                                <option value="python">Python</option>
                                                <option value="cpp">C++</option>
                                            </select>
                                        </div>
                                    </div>
                                    <button className="btn-premium w-full mt-4">
                                        Create Room <ChevronRight size={18} />
                                    </button>
                                </motion.form>
                            )}
                        </AnimatePresence>
                    </div>
                </motion.div>
            </div>
        </div>
    );
};
export default LandingPage;
